# 
# Copyright . All Rights Reserved.
#

version: '3.7'

services:

  pre-install:
    volumes:
      - ${WORK_DIR:-/home/docker}/crypto-config:/etc/hyperledger/crypto-config

  post-install:
    volumes:
      - ${WORK_DIR:-/home/docker}/crypto-config/hosts_orderer:/etc/hosts
      - ${WORK_DIR:-/home/docker}/crypto-config:/etc/hyperledger/crypto-config
#      - ${WORK_DIR:-/home/docker}/container-scripts:/etc/hyperledger/container-scripts # for local debug


  orderer:
    volumes:
      - ${WORK_DIR:-/home/docker}/crypto-config/hosts_orderer:/etc/hosts
      - ${WORK_DIR:-/home/docker}/crypto-config/configtx:/etc/hyperledger/configtx
      - ${WORK_DIR:-/home/docker}/crypto-config/ordererOrganizations/${DOMAIN:-example.com}/orderers/${ORDERER_NAME:-orderer}.${DOMAIN:-example.com}/:/etc/hyperledger/crypto/orderer
    ports:
      - ${ORDERER_GENERAL_LISTENPORT:-7050}:${ORDERER_GENERAL_LISTENPORT:-7050}

  cli.orderer:
    volumes:
      - ${WORK_DIR:-/home/docker}/crypto-config/hosts_orderer:/etc/hosts
      - ${WORK_DIR:-/home/docker}/crypto-config:/etc/hyperledger/crypto-config
#      - ${WORK_DIR:-/home/docker}/templates:/etc/hyperledger/templates
      - ${WORK_DIR:-/home/docker}/crypto-config/ordererOrganizations/${ORDERER_DOMAIN:-example.com}/orderers/${ORDERER_NAME:-orderer}.${ORDERER_DOMAIN:-example.com}:/etc/hyperledger/crypto/orderer
      - ${WORK_DIR:-/home/docker}/crypto-config/ordererOrganizations/${ORDERER_DOMAIN:-example.com}/users/Admin@${ORDERER_DOMAIN:-example.com}:/etc/hyperledger/crypto/ordereradmin

  # http serves certificates
  www.orderer:
    volumes:
      - ${WORK_DIR:-/home/docker}/crypto-config/ordererOrganizations/${DOMAIN:-example.com}/msp:/usr/share/nginx/html/msp
    ports:
      - ${WWW_PORT:-80}:80