NAMESPACE: &namespace default
logLevel: INFO # DEBUG

org: &org org1
peerName: peer0
domain: &domain default
#bootstrapIp: ''
#myIp: ""
authMode: ADMIN

peerOrgName: "{{ .Values.peerName }}-{{ .Values.org }}"

orderer_name: orderer

FABRIC_VERSION: 2.3.3

enroll_secret: adminpw

genesisBlock: crypto-config/configtx/{{ .Values.domain }}/genesis.pb

tmpDir: /tmp

images:
  fabric_tools_extended: olegabu/fabric-tools-extended:2x
  fabric_starter_rest: olegabu/fabric-starter-rest:2x
  dns_chaincode: olegabu/dns-chaincode:2x
  orderer: hyperledger/fabric-orderer:{{ .Values.FABRIC_VERSION }}
  peer: hyperledger/fabric-peer:{{ .Values.FABRIC_VERSION }}

peer0Port: 7051

common:
  env:
    - name: ORG
      value: *org
    - name: DOMAIN
      value: *domain


orderer:
  certificatePathes:
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/ca
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/admincerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/cacerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/msp/tlscacerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp/admincerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp/cacerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp/keystore
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp/signcerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/msp/tlscacerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/{{ .Values.orderer_name }}.{{ .Values.domain }}/tls
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/tlsca
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/admincerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/cacerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/keystore
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/signcerts
    - crypto-config/ordererOrganizations/{{ .Values.domain }}/users/Admin@{{ .Values.domain }}/msp/tlscacerts

peer:
  certificatePathes:
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/ca
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/keystore
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/signcerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/{{ .Values.peerName }}.{{ .Values.org }}.{{ .Values.domain }}/tls
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/tlsca
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/admincerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/cacerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/keystore
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/signcerts
    - crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/users/Admin@{{ .Values.org }}.{{ .Values.domain }}/msp/tlscacerts
