version: '2'

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:x86_64-1.0.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=dev-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./dev-msp:/etc/hyperledger/msp
      - ./dev-genesis.block:/etc/hyperledger/fabric/dev-genesis.block
    ports:
      - 7050:7050

  peer:
    container_name: peer
    image: hyperledger/fabric-peer:x86_64-1.0.0
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./dev-msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /etc/hyperledger
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/go:/opt/gopath/src
      - ./myc.block:/etc/hyperledger/myc.block
      - ./myc.tx:/etc/hyperledger/myc.tx
      - ./dev-msp:/etc/hyperledger/msp
    command: >
      bash -c "peer channel create -c myc -f myc.tx -o orderer:7050
      && peer channel join -b myc.block
      && sleep 600000
      && exit 0"
    depends_on:
      - orderer
      - peer

#  chaincode:
#    container_name: chaincode
#    image: hyperledger/fabric-ccenv
#    tty: true
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_LOGGING_LEVEL=DEBUG
#      - CORE_PEER_ID=example02
#      - CORE_PEER_ADDRESS=peer:7051
#      - CORE_PEER_LOCALMSPID=DEFAULT
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
#    working_dir: /opt/gopath/src
#    command: /bin/bash -c 'sleep 6000000'
#    volumes:
#      - /var/run/:/host/var/run/
#      - ./dev-msp:/etc/hyperledger/msp
#      - ../chaincode/go:/opt/gopath/src
#    depends_on:
#      - orderer
#      - peer
