#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  api.org1.example.com:
    build: ../server
    image: altoros/fabric-rest
    container_name: api.org1.example.com-dev
    ports:
      - "8080:8080"
    environment:
      - ORG=org1
    volumes:
      - ../artifacts:/usr/src/artifacts
      - ../server/app:/usr/src/app/app
      - ../server/lib:/usr/src/app/lib
      - ../server/web:/usr/src/app/web
    command: npm start

# api server for org2 disabled here