#
# Copyright . All Rights Reserved.
#

version: '3.7'


services:


  certs.generate:
    image: ${DOCKER_REGISTRY:-docker.io}/${FABRIC_STARTER_REPOSITORY:-olegabu}/fabric-tools-extended:${FABRIC_STARTER_VERSION:-baas-test-master-no-gost}
    container_name: certs-generate.${ORG:-org1}.${DOMAIN:-example.com}
    environment:
      - CERT_ORG=${ORG:-org1}.${DOMAIN:-example.com}
      - CERT_DAYS=${CERT_DAYS:-365}
      - CERT_COUNTRY=${CERT_COUNTRY:-US}
      - CERT_STATE=${CERT_STATE:-N/A}
      - CERT_ORGANIZATIONAL_UNIT=${CERT_ORGANIZATIONAL_UNIT:-Hyperledger Fabric Blockchain}
      - CERT_COMMON_NAME=${CERT_COMMON_NAME:-Fabric-Starter-Rest-API}
    command: /etc/hyperledger/container-scripts/certificates/generate_tls_cert.sh
    volumes:
      - ${SSL_CERTS_PATH:-./https/certs/}${ORG:-org1}.${DOMAIN:-example.com}:/certs
      - ${FABRIC_STARTER_HOME:-.}/crypto-config:/crypto-config
