#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

volumes:
  orderer.DOMAIN:

services:

  orderer.DOMAIN:
    container_name: orderer.DOMAIN
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      #- ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerORG1/tls/ca.crt, /etc/hyperledger/crypto/peerORG2/tls/ca.crt, /etc/hyperledger/crypto/peerORG3/tls/ca.crt]
      #TODO remove?
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /etc/hyperledger
    command: orderer
    ports:
      - ORDERER_PORT:7050
    volumes:
        - ../artifacts/channel:/etc/hyperledger/configtx
        - ../artifacts/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/:/etc/hyperledger/crypto/orderer
        - orderer.DOMAIN:/var/hyperledger/production/orderer
#        - ../artifacts/crypto-config/peerOrganizations/ORG1.DOMAIN/peers/peer0.ORG1.DOMAIN/:/etc/hyperledger/crypto/peerORG1
#        - ../artifacts/crypto-config/peerOrganizations/ORG2.DOMAIN/peers/peer0.ORG2.DOMAIN/:/etc/hyperledger/crypto/peerORG2
#        - ../artifacts/crypto-config/peerOrganizations/ORG3.DOMAIN/peers/peer0.ORG3.DOMAIN/:/etc/hyperledger/crypto/peerORG3

  cli.DOMAIN:
    container_name: cli.DOMAIN
    extends:
      file: base-intercept.yaml
      service: cli-base
    volumes:
        - ../artifacts/hosts/MAIN_ORG/cli_hosts:/etc/hosts
#      - ../artifacts/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/tls:/etc/hyperledger/crypto/orderer/tls


  # simple http server to disseminate certificates
  www.DOMAIN:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.DOMAIN
    ports:
      - WWW_PORT:80
