#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:

  pre-install:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug



  post-install:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug
    command: "sh" #container-scripts/install-default-chaincodes.sh


  peer0:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug


#  peer1:
#    volumes:
#      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
#      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug

  cli.peer:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug


  # fabric-rest api server
  api:
    volumes:
      - ${FABRIC_STARTER_HOME:-.}/templates:/etc/hyperledger/templates # for local debug
      - ${FABRIC_STARTER_HOME:-.}/container-scripts:/etc/hyperledger/container-scripts # for local debug

